# Autogenerated by update-version.py

__version__ = '2024.02.02'

RELEASE_GIT_HEAD = '264e9ff3fea7e5af4ae37b8ad835c11e8e57b770'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2024.02.02'
